<Project>
  <PropertyGroup>
    <Authors>Przemyslaw Klys</Authors>
    <Company>Evotec</Company>
    <RepositoryUrl>https://github.com/EvotecIT/PSTeams</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageProjectUrl>https://github.com/EvotecIT/PSTeams</PackageProjectUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageTags>MessageX;Messaging;Notifications;Teams;Slack;Discord;Webhooks</PackageTags>
    <Copyright>Copyright (c) Przemyslaw Klys and contributors</Copyright>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <EnablePackageValidation>true</EnablePackageValidation>
    <LangVersion>Latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <VersionPrefix>0.1.0</VersionPrefix>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(CI)' == 'true' ">
    <RestoreLockedMode>true</RestoreLockedMode>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net472'">
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="all" />
  </ItemGroup>
</Project>
